### ISSUE TITLE
Error when run iAnt-ARGoS-development on Mac

### ISSUE THREAD

**Issue by Linh-Tran** [BCLab-UNM/iAnt-ARGoS#5]
I have trouble running the new version of ARGoS under the development branch. 
I followed the steps as shown in the wiki page with the name of the file being iAnt-ARGoS-development.

I received this error prompt when I try to run make:

Undefined symbols for architecture x86_64:
  "iAnt_pheromone::Update(double)", referenced from:
      iAnt_data::UpdatePheromoneList() in iAnt_data.cpp.o
  "iAnt_pheromone::IsActive()", referenced from:
      iAnt_data::UpdatePheromoneList() in iAnt_data.cpp.o
  "argos::LOGERR", referenced from:
      iAnt_data::SetFoodDistribution() in iAnt_data.cpp.o
  "argos::CRandom::CRNG::Uniform(argos::CRange<double> const&)", referenced from:
      iAnt_data::RandomFoodDistribution() in iAnt_data.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [controllers/libiAnt_data.dylib] Error 1
make[1]: **\* [controllers/CMakeFiles/iAnt_data.dir/all] Error 2

Please provide instructions on how to resolve this issue.
Thank You,
Linh Tran

**Comment by lukey11-zz** [comment]
Yes! I got the same error.

**Comment by Antonio-Griego** [comment]
Thank you for reporting this error. The errors in your report are linking errors

There are a couple of things you can try:

---Delete the contents of the Build folder and recompile the code. If there are any errors preventing compilation please post those errors here in response. These are the steps:
1. delete the contents of the build folder
2. from the Terminal, cd into the build folder and run "cmake .."
3. then run "make"
4. cd back into the main folder "cd .."
5. try running the simulation again "argos3 -c experiments/iAnt.argos"

---I have updated the development branch with my most recent commits. Download the newest version of the development branch and see if you can compile and run that code. It compiles and runs for me on Linux, so if you are still having errors there is a localization problem with Macintosh.

**Comment by Antonio-Griego** [comment]
Well now... I have made several large modifications to the code and it should now work on BOTH Linux and Mac systems. The problem had to do with my old cmake files not properly linking the new iAnt_data class to the rest of the modules. Linux had no problems with this, but Mac was very persnickity...

Some important things to note: A new file structure has been introduced where all the source files are in 1 folder called "source". Your existing .argos configuration files will need to be updated to reflect this for your controllers and loop functions. For example:

"build/loop_functions/libiAnt_loop_functions" is now "build/source/libiAnt_loop_functions" (.so for linux or .dylib for mac)

and

"build/controllers/libiAnt_controller" is now "build/source/libiAnt_controller"

Furthermore, this version of the development code has new features that have not been properly documented or given easy to find flags in the XML... Those updates should be coming soon.

**Comment by lukey11-zz** [comment]
Hi Antonio,

Good morning!

I am running ARGoS on Ubuntu in the CS lab.

I got the code from the repository on the branch master. After cmake.. and
make the program I got the so files. I have to change the dylib file (e.g.
libiAnt_controller.dylib) to so file (e.g. libiAnt_controller.so) in the
XML file. Otherwise, it does not work.

Then I switch to the branch "lukey_development". I got the following errors,
[FATAL] Failed to initialize the space.
[FATAL] Error while trying to distribute entities
[FATAL] Failed to initialize entity "fb_00".
[FATAL] Failed to initialize controllable entity "controller_0".
[FATAL] Can't set controller for controllable entity "controller_0"
[FATAL] Node 'CPFA' not found

Then I switch to the branch ""development".  You said you added a new
folder "resource" and we need to change the path. Did you updated it? I
fund the path still in the previous folders, and could not work. After I
change back the path, I got the same errors on branch "lukey_development"
as shown above.

So, I tried to do cmake .. and make again. However, I got the message
"CMake 2.8.12 or higher is required.  You are running version 2.8.7" in the
terminal. I need to update CMake to a higher version, but I am not a sudoer
or root user.

Did I do anything wrong? Is there anyone know how to do? Thank you!

_Best regards!_

_Qi Lu (Lukey)_
Department of Computer Science
University of New Mexico

_Albuquerque, NM, 87109, USA_

_Office: FEC 329_

**Comment by Antonio-Griego** [comment]
Hello,

Just a couple of things to double check: The new folder for the source code is named "source" not "resource" so that may be a problem if you are using that in the XML.

You should be able to run the new version of ARGoS on your Mac again instead of the CS machines with the most recent update. This should help if you need to update any software it will be easier to do so from your local machine.

Updated Instructions for Mac:
1. delete the contents of the build folder
2. from the Terminal, cd into the build folder and run "cmake .."
3. then run "make"
4. cd back into the main folder "cd .."
5. try running the simulation with: "argos3 -c experiments/iAnt_mac.argos"

Let me know if this works.

**Comment by lukey11-zz** [comment]
Hi Antonio,

Thank you so much for your reply.

I did the typo "resource" for "source".

I followed your instruction on my mac, but it still does not work.

I did not see the generated dylib or so files. I attached two screenshots
to you. I will what happened on my mac. Thank you!

_Best regards!_

_Qi Lu (Lukey)_
Department of Computer Science
University of New Mexico

_Albuquerque, NM, 87109, USA_

_Office: FEC 329_
